### PR TITLE
Adding new timestamps

### PR DESCRIPTION
**Pull request by mykulh**
Added timestamps for:
From UNIX 32-bit Timestamp
To UNIX 32-bit Timestamp
From Mac Absolute Timestamp
To Mac Absolute Timestamp
From HFS(+) Timestamp
To HFS(+) Timestamp
From Windows 64-bit Filetime Timestamp
To Windows 64-bit Filetime Timestamp
From Chrome Browser Timestamp
To Chrome Browser Timestamp
From Firefox Browser Timestamp
To Firefox Browser Timestamp

### CODE REVIEW

**Comment by a3957273** [comment]
Hey! This pull request has gotten rather old and that's our fault. This project stopped being actively maintained for a while and it looks like your pull request has started to gather dust. Would you be able to update your branch to the latest version of CyberChef and we'll give it a review?

**Comment by mykulh** [comment]
I have tried to update my pull request, hopefully this has worked,
although Lint doesn't seem happy

**Comment by a3957273** [comment]
I'm confused, you seem to have closed and deleted the PR?

**Comment by mykulh** [comment]
Sorry, but GitHub suggested creating a new one due to the errors.
I thought I had created a new one?

**Pull request closed without merging**
