### PR TITLE
Operation: Multiple Steganography Operations

### PR DESCRIPTION
**Pull request by Ge0rg3**
This PR adds the ability to browse an image's bit planes, extract LSB data, and also simply extract an image's RGB(A) values.
These are widely seen as some of the most common forms of image steganography, and pop up in the good majority of CTFs today.

### CODE REVIEW

**Comment by Ge0rg3** [comment]
Will add tests in the next couple days :)

**Comment by n1474335** [comment]
Fantastic. Once you've got the tests in place I'll look at getting these merged. Great stuff.

**Comment by Ge0rg3** [comment]
Tests added, plus a simple RGBA extraction operation with custom delims.

**Comment by Ge0rg3** [comment]
Added one final steg tool - an operation for randomizing image colour palettes, which helps find text hidden in soft colours / in the background. A test has also been added for this :+1:

**Pull request merged**
