### PR TITLE
Use ES2016+ and webpack.

### PR DESCRIPTION
**Pull request by graingert**
This also removes the use of inline JS <script> tags and the eval() function.

### CODE REVIEW

**Comment by graingert** [comment]
sadly the version of gzip2 is very out of date. It's recommended to use compressjs instead: https://github.com/jvrousseau/bzip2.js/pull/2
https://github.com/skeggse/node-bzip
https://github.com/cscott/compressjs

**Comment by graingert** [comment]
@n1474335 do you have any views on this approach?

**Comment by graingert** [comment]
@n1474335 this is now completed for a modern project under webpack.

**Comment by graingert** [comment]
@n1474335 can you review this before there's too many conflicts

**Comment by n1474335** [comment]
Hey @graingert,

I'm impressed by your commitment! There are a lot of fairly major changes all in this one request and we're not in a position to merge them all at this time. We'll need to look at how this would fit in with our internal setup. I'm not against using some form of library management, but we need to consider which system is best suited.

I'm going to close this pull request as there are too many disparate concepts, but we will definitely take forward some of your ideas. Thank you for contributing.

**Pull request closed without merging**
