### PR TITLE
Add Moustache Template Operation

### PR DESCRIPTION
**Pull request by GCHQ77703**
screen shot 2018-08-26 at 20 41 01

### CODE REVIEW

**Comment by GCHQ77703** [comment]
I'm looking to add other templates, e.g. Jade (now Pug), EJS, etc.  Do you think it would be better to present these as different operations, or within a dropdown of this operation?

**Comment by n1474335** [comment]
That's a good question. In general we split this kind of functionality out into different operations because if someone wants to do something with a Mustache template, they're probably going to be looking for 'Mustache' rather than 'template'. However, in some cases we've rolled operations together, for instance the 'SHA2' operation handles SHA256, SHA512 etc.

Does anyone else have any thoughts?

**Comment by GCHQ77703** [comment]
May be new to this project, but your reasoning does make a lot of sense.

**Comment by n1474335** [comment]
Agreed, but perhaps we don't need to import the entire library. Is it possible to just pull in the bits we really need?

**Comment by d98762625** [comment]
Just looking at the library code here the main file `moustache.js` is only 22KB and there is no opportunity for named imports or anything like that. 

I think it would be reasonable to start a templating module.

**Pull request closed without merging**
