### PR TITLE
enable and auto-fix prefer template rule

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by n1474335** [comment]
Hi @graingert, I think this is another one where it's useful to run the autofix rule on the current repository, but I don't think we should insist on new contributors adhering to such strict rules, so let's remove it from the eslint config.

**Comment by graingert** [comment]
If it's a useful rule why not enforce it?

**Comment by n1474335** [comment]
See https://github.com/gchq/CyberChef/pull/126#issuecomment-299175980

**Comment by graingert** [comment]
But this is just a style change, and unlike the prefer const rule, it works
for all string concatenation. Linting makes writing code easier for
inexperienced developers because there's less choice in how code should be
written.

If someone makes a PR with a lint error, you can run the eslint fixer and
push to their branch

**Pull request closed without merging**
