### PR TITLE
Added ToTable operation to output data as ASCII or HTML tables.

### LINKED ISSUE #275: Operation request: Display CSV
### Summary

An operation to render a CSV input as a table would be useful. The output could either be an ASCII-style table or an HTML table. Ideally both of these formats would be supported and the user would be able to choose between them.

Support for TSVs could also be added.

### PR DESCRIPTION
**Pull request by JustAnotherMark**
This attempts to resolve #275 

This will be my first contribution to CyberChef so open to any feedback or corrections if I've missed anything.

Also, after starting work on this I noticed the ESM rewrite that's currently underway. Obviously, I'm happy for this PR to be ignored until that's complete and I can update it to work with the new system as required.

Screenshot of the new operation:
totable-operation-demo

### CODE REVIEW

**Comment by n1474335** [comment]
This looks great! Have you signed our [Contributor Licence Agreement](https://github.com/gchq/Gaffer/wiki/GCHQ-OSS-Contributor-License-Agreement-V1.0) so that I can merge this?

**Comment by JustAnotherMark** [comment]
@n1474335 Yeah, I sent the email agreeing to it on Monday. Should I have got any confirmation or anything?

**Comment by n1474335** [comment]
No, it just takes a while for it to get through to me. Thanks very much for the contribution, we'll definitely merge it soon.

**Comment by n1474335** [comment]
Awesome work @JustAnotherMark, thanks very much for this. I've made a few changes so that it's easier to support CSV, PSV and TSV file types. I've also switched to using the `Utils.parseCSV()` function as this handles strings with embedded delimiters a bit better. See [this example](https://gchq.github.io/CyberChef/#recipe=To_Table(',','%5C%5Cn%5C%5Cr',true,'ASCII')&input=77u/b25lLHR3byx0aHJlZQphLGIsYwpsb25nLCJ2YWx1ZSwgd2l0aCBhIGNvbW1hIGluIGl0Iixsb25nCnF1b3RlLCdoZWxsbycscXVvdGUKcXVvdGUsIiIid29ybGQiIiIscXVvdGUK).

Thanks for the contribution, this will be particularly useful and ticks another one off the list.

**Pull request merged**
