### PR TITLE
fix spelling mistakes and grammar

### PR DESCRIPTION
**Pull request by ashna-ashu**

### CODE REVIEW

**Comment by Cal-Hagner** [comment]
A few of the "mistakes" you marked are not mistakes, merely incongruities between American English and UK English - i.e. reorgani**z**ed in America is reorgani**s**ed in the UK. GCHQ is a UK-based organization, so it makes sense that their spellings would match the UK spellings, but not necessarily the American ones.

**Comment by n1474335** [comment]
Thanks for contributing, however I'm afraid I'm going to close this. It's a duplicate of several other low effort PRs we have received recently, presumably the result of an automated script. Please check existing PRs before contributing.

I would also direct you towards the quality standards section of the Hacktoberfest website (which I assume this is part of): https://hacktoberfest.digitalocean.com/details#quality-standards

**Comment by Xenonym** [comment]
@n1474335 [you (or another maintainer) can help to label spam PRs as `invalid`](https://hacktoberfest.digitalocean.com/details#spam) to help maintain the standards of PRs during Hacktoberfest:
> If you’re a maintainer, please label any spammy PRs submitted to the repositories you maintain as `invalid`, and close them. PRs with this label won't count toward Hacktoberfest.

**Comment by MarcusJohnson91** [comment]
You're an American hero, keep up the good work patriot.

**Comment by samvdkris** [comment]
You absolute madlad

**Pull request closed without merging**
