### PR TITLE
Morse code improvements

### PR DESCRIPTION
**Pull request by misterRaven**
- Added punctuation symbols for Morse code
- FromMorse operation made to treat dashes & hyphens as long signal; interpunct as short signal

### CODE REVIEW

**Comment by n1474335** [comment]
Looks good, have you signed the [CLA](https://github.com/gchq/Gaffer/wiki/GCHQ-OSS-Contributor-License-Agreement-V1.0)? Once that's done we'll merge.

**Comment by n1474335** [comment]
It might be worth also adding the non-English extensions which [can be found here](https://en.wikipedia.org/wiki/Morse_code#Letters.2C_numbers.2C_punctuation.2C_prosigns_for_Morse_code_and_non-English_variants) (there are about 31 at the bottom of the table).

**Comment by misterRaven** [comment]
Most of those sequences are shared by several characters, so they can only be translated in context of some specific alphabet. I think it's better not to add them.

**Comment by misterRaven** [comment]
And yes, I signed CLA

**Comment by n1474335** [comment]
Hi @misterRaven, I'm afraid we haven't received your [CLA ](https://github.com/gchq/Gaffer/wiki/GCHQ-OSS-Contributor-License-Agreement-V1.0)email, could you resend it?

**Comment by misterRaven** [comment]
I resent CLA email on Feb 15

**Comment by n1474335** [comment]
Thank you, we have now received it. Merging now.

**Pull request merged**
