### PR TITLE
Get Public Key from a Certificate or from a Private Key

### PR DESCRIPTION
**Pull request by cplussharp**
Add two new operations. One operation to get the public key of a given certificate and another one to get the public key for a given private key.

### CODE REVIEW

**Comment by cplussharp** [comment]
Rebased changes to the current master

**Comment by cplussharp** [comment]
this fixes #1793

**Comment by a3957273** [comment]
Very nice contribution.  I've tried this in the past and it's not particularly easy to do this on the fly.

**Comment by cplussharp** [comment]
Thanks for the merge

**Pull request merged**
