### PR TITLE
Fixed tesseract issue

### LINKED ISSUE #993: Bug report: Optical Character Recognition erroring on PNG input
**Describe the bug**
Trying OCR with a PNG file (only tested with PNG, may well fail for other filetypes) fails with error
```
Error performing OCR on image. (TypeError: T is not a constructor)
```

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Drag any PNG file into the input pane
2. Use the Optical Character Recognition operation

**Expected behaviour**
Should attempt to extract text from image file

Fails on both stable Chrome and latest Firefox Developer Edition on latest Linux kernel and latest Windows stable.

### PR DESCRIPTION
**Pull request by mattnotmitt**
Fixes #993.
Issue was that we had updated the tesseract script loaded in the browser but not the "offline" files (worker script and core tesseract wasm). Added extra webpack config to prevent this in future & changed construction of tesseract object to new format.

### CODE REVIEW

**Comment by mattnotmitt** [comment]
@n1474335 any reason why this hasn't been merged?

**Comment by d98762625** [comment]
Hi @mattnotmitt, I'm having issues running this locally:

- git clone https://github.com/mattnotmitt/CyberChef.git
- git checkout fixes/tesseract-ocr
- npm install
- npm start

go to localhost:8080
drag a PNG into input and select Optical Character Recognition

The output I get is:
```
Error performing OCR on image. (abort(Assertion failed: ClassTemplate->ProtoLengths[ActualProtoNum] < MAX_PROTO_INDEX, at: /src/src/classify/intmatcher.cpp,1155,UpdateSumOfProtoEvidences). Build with -s ASSERTIONS=1 for more info.)
```
Before this, it shows the loading animation and the `analyzing text` progress running up to 100%

**Comment by mattnotmitt** [comment]
@d98762625 could you check if your image works on [tesseract's own example site](https://tesseract.projectnaptha.com/)? I've just pulled this down and tried it again and it still seems to work with all the example images I tried. Running latest Firefox on mainline Linux kernel which might be a contributing factor.

**Comment by d98762625** [comment]
yep you're right, the test image I used failed on tesseract's landing page too.

I've found an image that works on tesseract.js and it also works on chef. Cheers 👍

**Comment by d98762625** [comment]
@mattnotmitt just rebased your branch

**Pull request merged**
