### PR TITLE
Added BytesToLong and LongToBytes

### PR DESCRIPTION
**Pull request by clubby789**
Add a pair of functions to convert an array of bytes to a single long integer, and to do the reverse.

### CODE REVIEW

**Comment by chengxuncc** [comment]
What you expected are `From Base` and `To Base`?

**Comment by clubby789** [comment]
@chengxuncc I'm not sure what you mean, can you elaborate?

**Comment by chengxuncc** [comment]
https://gchq.github.io/CyberChef/#recipe=To_Base(16)&input=MTIzNDU2Nzg5MA
https://gchq.github.io/CyberChef/#recipe=From_Base(16)&input=ZGEzOWEzZWU1ZTZiNGIwZDMyNTViZmVmOTU2MDE4OTBhZmQ4MDcwOQ

**Comment by clubby789** [comment]
This translates between a decimal integer and a string, if that’s what you mean

**Comment by chengxuncc** [comment]
https://gchq.github.io/CyberChef/#recipe=To_Base(16)From_Hex('Auto')&input=NTI5ODM2NzE4NDI4NDQ3MjIyNDcxNzk2Mzk2MTkzMzIzMTgxMjQwNzQyMzAwNjk1NTk0MTQ1ODM0Nzg1

**Comment by clubby789** [comment]
I believe it's useful to have a dedicated method for this, as opposed to a roundabout recipe with multiple blocks

**Comment by mikecat** [comment]
To add, this method using "To Base" and "From Hex" fails when the first byte is in the range 0x01 - 0x0f (only have 1 digit instead of 2).
It should be nice to having a way to handle this automatically.

Example:

Encoding: [To Hex, From Base - CyberChef](https://gchq.github.io/CyberChef/#recipe=To_Hex%28%27None%27,0%29From_Base%2816%29&input=CXRlc3Q)
Decoding (fails): [To Base, From Hex - CyberChef](https://gchq.github.io/CyberChef/#recipe=To_Base%2816%29From_Hex%28%27Auto%27%29&input=NDA2MDc1MTE0MTI)

**Comment by a3957273** [comment]
Hey! This pull request has gotten rather old and that's our fault. This project stopped being actively maintained for a while and it looks like your pull request has started to gather dust. Would you be able to update your branch to the latest version of CyberChef and we'll give it a review?

**Comment by clubby789** [comment]
Looks like GH permanently closed this while trying to rename my branch 🤔 I'll open a new PR

**Pull request closed without merging**
