### PR TITLE
AAD for AES Added

### LINKED ISSUE #1008: Feature request: AAD in AES GCM mode
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]
AES Encrypt/Decrypt GCM mode does not support Additional Authenticated Data (AAD).

**Describe the solution you'd like**
Support for AAD in GCM mode.

**Describe alternatives you've considered**
Python cryptography or python cryptodomex. 

**Additional context**
GCM mode has an additional authenticated data feature that allows you to feed extra data into the cipher to be authenticated. Without support for this feature verification fails for ciphertext and encryption will output the incorrect tag when additional authenticated data is present. Either add the ability to include AAD or add a checkbox to ignore the tag. Preferably the former, but the latter would be a quicker fix.

### PR DESCRIPTION
**Pull request by n1073645**
Upon closer inspection, forge does support Authenticated Additional Data. So here it is. 

Closes #1008

### CODE REVIEW

**Comment by mubix** [comment]
Really looking forward to this feature 👍

**Comment by n1474335** [comment]
I added support for AAD in the AES Decrypt operation too, and wrote a bunch of tests based on results generated from pycryptodome.

**Comment by ch0wm3in** [comment]
What kind of input is expected in this?
Is it hex, raw, utf-8?

**Comment by n1474335** [comment]
Good point. I originally implemented it as a binary string (so you could include non-printable characters in their escaped form, like `\n` or `\x0a`) but I've just changed it so you can specify the type, like for the key and IV.

**Pull request merged**
