### PR TITLE
Tauri desktop App for more UX offline usage

### PR DESCRIPTION
**Pull request by z4nr34l**
To build app just run `npm run tauri build`, the build artifacts would be in `<project-dir>/src-tauri/target/release/bundle/`.

Tested on macOS (M1), works like a charm as build process is as simple as possible ;)

Feel free to overwrite config files to suite your needs.

Regards and Happy New Year!

### CODE REVIEW

**Comment by z4nr34l** [comment]
Solving #1074

**Comment by z4nr34l** [comment]
WIP: Automating app building according to existing workflow

**Comment by z4nr34l** [comment]
App build automation is ready, can't test Windows build as #1306 still occurs

**Comment by z4nr34l** [comment]
Finished, able to merge

**Comment by z4nr34l** [comment]
Closing as stale

**Comment by a3957273** [comment]
Hey @z4nr34l.  Apologies for the delay in getting to this.  If you'd be willing to update this / unclose, I'd be happy to review and try to get this in!

**Pull request closed without merging**
