### PR TITLE
RSA Operations

### PR DESCRIPTION
**Pull request by mattnotmitt**
Fulfilling #272.
- [x] Generate RSA Key Pair
- [x] RSA Sign
- [x] RSA Verify
- [x] RSA Encrypt
- [x] RSA Decrypt

### CODE REVIEW

**Comment by mattnotmitt** [comment]
@d98762625 This PR is ready for review finally btw :)

**Comment by binlab** [comment]
Nice work!

**Comment by mattnotmitt** [comment]
Currently discussing the issue with the tests in https://github.com/digitalbazaar/forge/issues/783. It does work if we use un-minified forge but I'm not sure we want to do that just so these tests pass.

**Comment by d98762625** [comment]
Cheers @mattnotmitt I can take a look tomorrow but this will need the OK from @n1474335 because its a new operation 👍

**Comment by Traderain** [comment]
Why isn't this merged?

**Comment by mattnotmitt** [comment]
> Why isn't this merged?

Couple people have asked me this (on Twitter) and after contacting the lead maintainer this is the reply I got:

> "Hey, yes I hope to be [back to merging]. My time has been very stretched over the last year, but I hope to get back to it at some point." - @n1474335

**Comment by n1474335** [comment]
This took a little bit of tidying up regarding UTF-8 input, but I have got the tests working and integrated.

Thanks very much for the time and effort you have put into implementing this!

**Pull request merged**
