### PR TITLE
Feature/improve email extract

### PR DESCRIPTION
**Pull request by klaxon1**
To resolve https://github.com/gchq/CyberChef/issues/365
Used email regex from https://www.regular-expressions.info/email.html
Added some basic tests.
The following email address are valid:
``
email@example.com
firstname.lastname@example.com
email@subdomain.example.com
firstname+lastname@example.com
1234567890@example.com
email@example-one.com
_______@example.com
email@example.name
email@example.museum
email@example.co.jp
firstname-lastname@example.com
``

### CODE REVIEW

**Comment by edent** [comment]
Does this work with I18n domain names?

For example `test@莎士比亚.org`

(from https://shkspr.mobi/blog/2016/09/why-cant-you-send-email-to-a-chinese-address/)

**Comment by GCHQ77703** [comment]
It does not appear to.  Nor does it appear to work with any non-latin characters anywhere in the email address.  E.g:

    gâteau@cake.com

**Comment by klaxon1** [comment]
good point all, i didnt consider those cases. lets leave this pull request open and i'll make some additional commits.

**Comment by klaxon1** [comment]
so, I've learnt this week that email addresses are more complicated then i originally thought.
Hopefully this updated regex (from https://www.regextester.com/98066) seems to match 99% of valid email addresses.
The following email address are all extracted successfully:
```
伊昭傑@郵件.商務
म@मोहन.ईन्फो
юзер@екзампл.ком
θσερ@εχαμπλε.ψομ 
JosễSilvễ@googlễ.com
JosễSilvễ@google.com 
JosễSilva@google.com
FoO@BaR.CoM
john@192.168.10.100
gómez@junk.br
Abc.123@example.com.
user+mailbox/department=shipping@example.com
用户@例子.广告
उपयोगकर्ता@उदाहरण.कॉम
юзер@екзампл.ком
θσερ@εχαμπλε.ψομ
Dörte@Sörensen.example.com
аджай@экзампл.рус
test@xn--bcher-kva.com
gâteau@cake.com
test@莎士比亚.org
email@example.com
firstname.lastname@example.com
email@subdomain.example.com
firstname+lastname@example.com
1234567890@example.com
email@example-one.com
_______@example.com
email@example.name
email@example.museum
email@example.co.jp
firstname-lastname@example.com
```

**Comment by n1474335** [comment]
Excellent, thanks very much for this. I haven't updated the built in email regex in the 'Regular Expression' operation as I feel this version should be a bit more quick and dirty. It's useful to have a fairly accurate one for 'Extract email addresses' though.

**Pull request merged**
