### PR TITLE
Edit build for inline to avoid Safari unicode regex error

### PR DESCRIPTION
**Pull request by d98762625**
Attempts to solve #414.

Use custom uglifyJS plugin on inline build so that we can switch the `ascii_only` flag, which escapes unicode chars in strings and regex. This avoids the `SyntaxError: Invalid regular expression: range out of order in character class` that I was seeing.

- `cache` and `parallel` options are just for speed.
- Changes to `webpack.config.js` Remove errors occuring from using custom UglifyJS plugin instance.

### CODE REVIEW

**Comment by n1474335** [comment]
Thanks for looking into this.

Does this emulate all UglifyJS options that are set if webpack is left to do the minification itself?
Do you know if this significantly effects the size of the inline version?

**Comment by n1474335** [comment]
I wonder why this is only an issue in the inline version and not the normal production version too. Could it be an issue with the inliner? I would rather fix it there if possible to avoid having to maintain the UglifyJS configuration.

**Comment by d98762625** [comment]
Considering where the error arises, it must be caused by the inliner somewhere.

The size difference is significant - 9.7MB before, 11MB after.

Seeing as we have a temporary workaround, we could spend more time investigating whether we can nail it down to the inliner.

**Comment by d98762625** [comment]
Interestingly this isn't an issue arising from `web-resource-inliner`. I'll close this PR for now and keep documenting on the issue for consistency.

**Comment by d98762625** [comment]
I think the workaround for this (running `http-server` with gzip flag) is convenient enough to avoid the +2MB size increase of editing the minification config. I will update the wiki with guidance and close this PR

**Pull request closed without merging**
