### PR TITLE
All Case Variations Of String

### LINKED ISSUE #1060: Output: All Possible Casing Variations of a String
It would be great to have a function that outputs all possible casing variations of a string. 

e.g. "cmd.exe > "Cmd.exe", "CMd.exe" ... 

Here's an example on how to do it in Python: 
https://gist.github.com/Neo23x0/276e45ee1d747c6db672363b69a6b491

Screenshot 2020-07-02 at 16 24 17

### PR DESCRIPTION
**Pull request by n1073645**
Closes #1060

### CODE REVIEW

**Comment by Neo23x0** [comment]
Any updates on this?

**Comment by Neo23x0** [comment]
b16

**Comment by sebastianganson** [comment]
Plus 1

Best,
Sebastian

**Comment by pH-T** [comment]
hi, 
there seems to be a bug in this function: https://gchq.github.io/CyberChef/#recipe=Get_All_Casings()Unique('Line%20feed')Fork('%5C%5Cn','%5C%5Cn',false)Show_Base64_offsets('A-Za-z0-9%2B/%3D',false,'Raw')&input=aWV4

"Get All Casings" adds a '\n' to the end and it looks like this breaks functions like "Show Base64 offsets".
see https://github.com/gchq/CyberChef/pull/1327 for a possible fix.

**Pull request merged**
