### PR TITLE
Add Base45 operations

### LINKED ISSUE #1219: Feature request: base45 decoding
**Is your feature request related to a problem? Please describe.**
I tried to decode base45 but the "From Base" only goes up to 36

**Describe the solution you'd like**
Decode the base45 data described by this: https://github.com/patrikhson/base45

**Describe alternatives you've considered**
I currently use the original tool

### PR DESCRIPTION
**Pull request by t-8ch**
Closes #1219

### CODE REVIEW

**Comment by nielsbasjes** [comment]
I was looking into decoding the vaccination QR code (which uses Base45) and ran into this tweet which seems to indicate that there are variants of this encoding: https://mobile.twitter.com/jilles_com/status/1416758126372663305

It would be nice if these variants can be supported too.

**Comment by t-8ch** [comment]
@nielsbasjes The EU specification does not specify any variants. Are they documented somewhere properly?

**Comment by t-8ch** [comment]
FYI to properly decode the EU green pass files CyberChef will also need support for COSE

**Comment by nielsbasjes** [comment]
Ik have also not been able to find a good specification yet.
The best sources I have are the tweet I mentioned which shows a code fragment and this (Dutch) article which also mentions ASN.1 as being part of the Dutch variant. 
https://tweakers.net/reviews/9166/het-digitale-coronapaspoort-hoe-de-app-om-te-kunnen-reizen-werkt.html

If I find something better I'll post it here.

**Comment by nielsbasjes** [comment]
It seems there are several publicly available photos that seem to actually show a valid (expired) Dutch QR code:
https://twitter.com/MinVWS/status/1438433503205597192/photo/1
https://www.ewmagazine.nl/nederland/achtergrond/2021/09/radicale-omslag-coronabeleid-toegangsbewijs-voor-horeca-en-theater-geen-afstandsregel-844321/

Note there are also a lot of images that have fake content. These two seem to contain (at a first glance) content that makes sense.

**Comment by nielsbasjes** [comment]
The code for the Dutch apps was opensourced by the Dutch government: https://github.com/minvws/nl-covid19-coronacheck-app-coordination

**Comment by t-8ch** [comment]
This seems to be their base 45 implementation:
https://github.com/minvws/base45-go

The rest of their implementation is in https://github.com/minvws/nl-covid19-coronacheck-mobile-core and https://github.com/minvws/nl-covid19-coronacheck-idemix

A few notes:
* I think this is a completely different encoding than the one from this PR, so it probably should get its own dedicated operation.
* There is no public specification, so you would have to work from the code which is licensed as EUPL, for which I'm not sure if it's compatible with the CyberChef license.

**Comment by nielsbasjes** [comment]
I fully agree.
This dutch encoding must be treated completely separate from this merge request.

**Pull request merged**
